development:
  adapter: postgresql
  encoding: unicode
  database: documents_development
  pool: 5
  username: justin
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: documents_test
  pool: 5
  username: justin
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: documents_production
  pool: 5
  username: justin
  password:
